// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default']
    NeuButton: typeof import('./components/NeuButton.vue')['default']
    NeuButton2: typeof import('./components/NeuButton2.vue')['default']
    NeuButton3: typeof import('./components/NeuButton3.vue')['default']
    NeuProgress: typeof import('./components/NeuProgress.vue')['default']
    NeuSlider: typeof import('./components/NeuSlider.vue')['default']
    NeuSwitch: typeof import('./components/NeuSwitch.vue')['default']
    NeuSwitch2: typeof import('./components/NeuSwitch2.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export { }
